# Site wide configuration

title: Code Espresso
locale: en_US
description: Compressed Tips for Faster Development and Deployment
logo: espresso-logo.jpg
search: true
url: https://cindyc.github.io/codespresso/

# Filtering Content
show_drafts: null

# Serving
baseurl: "" # does not include hostname

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Cindy Cao
  avatar: twitter_profile.jpg
  email: cindy.hy.cao@gmail.com
  disqus-shortname: rcync
  twitter: Sla5hd0t
  facebook: #username
  github: cindyc
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: rcync
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
